// Embeds every Vox source under src/ into the launcher binary, the same way
// the vox compiler embeds its coreasm (plan 312). Walking the directory at
// build time means a newly added .vox module ships with no list to update.
use std::{env, fs, path::Path};

fn main() {
    let out = env::var("OUT_DIR").unwrap();
    let mut entries: Vec<(String, String)> = Vec::new();

    let src = Path::new("src");
    for entry in fs::read_dir(src).expect("read src/") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) == Some("vox") {
            let name = path.file_name().unwrap().to_str().unwrap().to_string();
            let body = fs::read_to_string(&path).expect("read a .vox source");
            println!("cargo:rerun-if-changed=src/{name}");
            entries.push((name, body));
        }
    }
    entries.sort();

    let mut generated = String::from(
        "// Generated by build.rs — every src/*.vox, embedded.\n\
         pub static VOX_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (name, body) in &entries {
        generated.push_str(&format!("    ({name:?}, {body:?}),\n"));
    }
    generated.push_str("];\n");

    fs::write(Path::new(&out).join("vox_sources.rs"), generated).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}
